# Project information
site_name: "Turn-key research data management repository"
site_url: "https://inveniordm.docs.cern.ch"

# Repository
repo_url: "https://github.com/inveniosoftware/docs-invenio-rdm"

# Copyright
copyright: "Copyright &copy; 2019-2024 CERN, Northwestern University and contributors."

# Configuration
theme:
  name: material
  custom_dir: theme
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      extra_css:
        - stylesheets/extra.css
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: orange
      toggle:
        accent: orange
        icon: material/brightness-4
        name: Switch to light mode
  font: false
  logo: "images/logo-rdm.png"
  favicon: "images/favicon.svg"
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.copy

nav:
  - Home: "index.md"
  - Features:
      - Overview: "features/index.md"
      - Beautiful UX: "features/ux.md"
      - Highly scalable: "features/scalable.md"
      - Customizable: "features/customization.md"
      - Interoperable: "features/interoperable.md"
      - Powerful: "features/powerful.md"
      - Secure: "features/secure.md"
      - Features walk-through:
          - Features overview: "features/features-walk-through/index.md"
          - Site banners: "features/features-walk-through/banners.md"
          - Notifications: "features/features-walk-through/notifications.md"
          - Access requests: "features/features-walk-through/access_requests.md"
          - Restricted records: "features/features-walk-through/restricted_records.md"
          - Metadata-only records: "features/features-walk-through/metadata_only.md"
  - Install:
      - Quick start: "install/index.md"
      - System requirements: "install/requirements.md"
      - Install CLI: "install/cli.md"
      - Scaffold: "install/scaffold.md"
      - Build, setup & run: "install/build-setup-run.md"
      - Configure: "install/configuration.md"
      - Use: "install/run.md"
      - Migrate: "install/migrate.md"
      - Destroy: "install/destroy.md"
      - Troubleshooting: "install/troubleshoot.md"
  - Customize:
      - Overview: "customize/index.md"
      - Look-and-feel:
          - Overview: "customize/look-and-feel/index.md"
          - Change logo: "customize/look-and-feel/logo.md"
          - Change templates: "customize/look-and-feel/templates.md"
          - Change theme: "customize/look-and-feel/theme.md"
          - Change font: "customize/look-and-feel/font.md"
      - Authentication: "customize/authentication.md"
      - Sending emails: "customize/emails.md"
      - Search:
          - Change facets/sorting: "customize/search.md"
      - Vocabularies:
          - Overview: "customize/vocabularies/index.md"
          - Resource types: "customize/vocabularies/resource_types.md"
          - Affiliations: "customize/vocabularies/affiliations.md"
          - Names: "customize/vocabularies/names.md"
          - Funding: "customize/vocabularies/funding.md"
          - Subjects: "customize/vocabularies/subjects.md"
          - Users: "customize/vocabularies/users.md"
      - Metadata:
          - Optional metadata: "customize/metadata/optional_fields.md"
          - Custom fields:
            - Add fields to records: "customize/metadata/custom_fields/records.md"
            - Add fields to communities: "customize/metadata/custom_fields/communities.md"
      - Record landing page: "customize/record_landing_page.md"
      - Static pages: "customize/static_pages.md"
      - DOI registration: "customize/dois.md"
      - Other PIDs integrations:
          - DNB URNs: "customize/other-pids/urns.md"
      - Storage: "customize/s3.md"
      - Upload Limits: "customize/upload_limits.md"
      - Metadata-only records: "customize/metadata_only.md"
      - Logging: "customize/Logging.md"
      - Internationalisation (i18n) and Localisation (l10n): "customize/i18n-and-l10n.md"
      - Notifications: "customize/notifications.md"
  - Develop:
      - Overview: "develop/index.md"
      - Getting started:
          - Source code: "develop/getting-started/source-code.md"
          - Package development: "develop/getting-started/package-development.md"
          - Instance development: "develop/getting-started/instance-development.md"
          - Debugging: "develop/getting-started/debugging.md"
          - Coding style: "develop/getting-started/code-style.md"
          - Virtual environments: "develop/getting-started/virtualenvs.md"
          - Getting help: "develop/getting-started/help.md"
          - Development process: develop/process.md
      - Best practices:
          - Accessibility (a11y): develop/best-practices/accessibility.md
          - Commits, PRs & reviews: develop/best-practices/commits.md
          - CSS/JavaScript: develop/best-practices/css-js.md
          - React: develop/best-practices/react.md
          - User interface: develop/best-practices/ui.md
      - Topic guides:
          # - Building REST APIs: develop/topics/rest.md
          - Building resources: develop/topics/resource.md
          - Building services: develop/topics/service.md
          # - Building records: develop/topics/record.md
          # - Building system fields: develop/topics/systemfield.md
          - Building serializers: develop/topics/serializers.md
          - Grouping atomic operations: develop/topics/uow.md
          - Sanitize input data: develop/topics/validation.md
          - Theming: develop/topics/theming.md
          - Administration panel: develop/topics/administration_panel.md
      - How-to guides:
          - Translation (i18n): develop/howtos/i18n.md
          - Create a new custom field: develop/howtos/custom_fields.md
          - Create custom code and views: develop/howtos/custom_code.md
          - Add JavaScript: "develop/howtos/add_javascript.md"
          - Override UI React components: develop/howtos/override_components.md
          - Create search terms mappings: develop/howtos/search_terms_migration.md
          - Create a database migration: develop/howtos/alembic.md
          - Fix a vulnerability: develop/howtos/security-fix.md
          - Test emails locally: develop/howtos/dev_email.md
          - Migrate legacy routes: develop/howtos/route_migration.md
          - Back up search indices: develop/howtos/backup_search_indices.md
          - Restrict access to pages: develop/howtos/restrict_access.md
          - Create and configure notifications: develop/howtos/notifications.md

      - Architecture:
          - Introduction: develop/architecture/index.md
          - Infrastructure: develop/architecture/infrastructure.md
          - Software: develop/architecture/software.md
          - Runtime: develop/architecture/runtime.md
          - Requests: develop/architecture/requests.md
          - Communities: develop/architecture/communities.md
          - Records: develop/architecture/records.md
          - Event handling: develop/architecture/event_handling.md
          - Notifications: develop/architecture/notifications.md
          - Recommended reading: develop/architecture/reading.md
      - Concepts:
          - Optimistic concurrency control: develop/concepts/concurrency-control.md
          - Database transaction management: develop/concepts/transactions.md
  - Deploy: deploy/index.md
  - Reference:
      - Overview: reference/index.md
      - CLI: reference/cli.md
      - Configuration: reference/configuration.md
      - Metadata: reference/metadata.md
      - Optional metadata: reference/metadata/optional_metadata.md
      - OAI-PMH: reference/oai_pmh.md
      - Export formats: reference/export_formats.md
      - REST API:
          - Overview: "reference/rest_api_index.md"
          - Quickstart: "reference/rest_api_quickstart.md"
          - Communities: "reference/rest_api_communities.md"
          - Drafts and Records: "reference/rest_api_drafts_records.md"
          - Groups: "reference/rest_api_groups.md"
          - Members: "reference/rest_api_members.md"
          - Requests: "reference/rest_api_requests.md"
          - Users: "reference/rest_api_users.md"
          - Reviews: "reference/rest_api_reviews.md"
          - Vocabularies: "reference/rest_api_vocabularies.md"
          - Names: "reference/rest_api_names.md"
          - Funders: "reference/rest_api_funders.md"
          - Awards: "reference/rest_api_awards.md"
          - OAI-PMH Sets: "reference/rest_api_oaipmh_sets.md"
          - Statistics: "reference/rest_api_statistics.md"
      - Custom fields:
          - UI widgets: "reference/custom_fields/widgets.md"
      - Administration:
          - Reference: "reference/administration_reference.md"
      - File storage: "reference/file_storage.md"
      - Usage statistics: "reference/statistics.md"
      - Notifications: "reference/notifications.md"
      - Searching: "reference/search.md"

  - Releases:
    - Overview: releases/index.md
    - Maintenance policy: releases/maintenance-policy.md
    - Upgrade policy: releases/upgrade-policy.md
    - Security policy: releases/security-policy.md
    - WIP - Version v13.0 STS:
      - Release Notes v13.0: releases/v13/version-v13.0.0.md
      - Upgrade from v12 to v13: releases/v13/upgrade-v13.0.md
    - Version v12.0 LTS:
      - Release Notes v12.0: releases/v12/version-v12.0.0.md
      - Upgrade from v11 to v12: releases/v12/upgrade-v12.0.md
    - Version v11.0 STS:
      - Release Notes v11.0: releases/v11/version-v11.0.0.md
      - Upgrade from v10 to v11: releases/v11/upgrade-v11.0.md
    - Version v9.1 LTS:
      - Release Notes v9.1: releases/v9/version-v9.1.0.md
      - Release Notes v9.0: releases/v9/version-v9.0.0.md
      - Migrate Docker images: releases/migrate-docker-images.md
      - Migrate v9 to OpenSearch: releases/v9/migrate-opensearch-v9.md
      - Upgrade from v8 to v9: releases/v9/upgrade-v9.0.md
    - Legacy Versions:
      - Version v10.1:
        - Release Notes v10.1: releases/v10/version-v10.1.0.md
        - Release Notes v10.0: releases/v10/version-v10.0.0.md
        - Upgrade from v9 to v10: releases/v10/upgrade-v10.0.md
        - Migrate Docker images: releases/migrate-docker-images.md
      - Version v8.0:
        - Release Notes v8.0: releases/v8/version-v8.0.0.md
        - Upgrade from v7 to v8: releases/v8/upgrade-v8.0.md
      - Version v7.0:
        - Release Notes v7.0: releases/v7/version-v7.0.0.md
        - Upgrade from v6 to v7: releases/v7/upgrade-v7.0.md
      - Version v6.0.5:
        - Release Notes v6.0.5: releases/v6/version-v6.0.5.md
        - Upgrade from v6.0.x to v6.0.5: releases/v6/upgrade-v6.0.5.md
        - Release Notes v6.0.0: releases/v6/version-v6.0.0.md
        - Upgrade from v4 to v6: releases/v6/upgrade-v6.0.md
      - Version v5.0:
        - Release Notes v5.0: releases/v5/version-v5.0.0.md
      - Version v4.0:
        - Release Notes v4.0: releases/v4/version-v4.0.0.md
        - Upgrade from v3 to v4: releases/v4/upgrade-v4.0.md
      - Version v3.0:
        - Release Notes v3.0: releases/v3/version-v3.0.0.md
        - Upgrade from v2 to v3: releases/v3/upgrade-v3.0.md
      - Version v2.0:
        - Release Notes v2.0: releases/v2/version-v2.0.0.md
        - Upgrade from v1 to v2: releases/v2/upgrade-v2.0.md
      - Version v1.0:
        - Release Notes v1.0: releases/v1/version-v1.0.0.md

  - Maintainers:
      - Overview: maintenance/index.md
      - Newcomers: maintenance/newcomers.md
      - Sprintboard workflow: maintenance/board-workflow.md
      - Community PR board: maintenance/pr-community-board.md
      - Release management: maintenance/release-management.md
      - Modules on GitHub: maintenance/modules.md
      - Branch management: maintenance/branch-management.md
      - Demo site & docs: maintenance/demosite.md
      - Docker images: maintenance/docker-images.md
      - RFCs: maintenance/rfcs.md
      - Writing documentation: maintenance/documentation.md
  - Onboard & Contribute:
      - Overview: contribute/index.md
      - Onboarding: contribute/onboarding.md
      - Code of conduct: contribute/code-of-conduct.md
      - Copyright policy: contribute/copyright-policy.md
      - Roadmap: contribute/roadmap.md
      - Translators guide: contribute/translators-guide.md

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/inveniosoftware
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.critic

  - toc:
      permalink: true
