# Project information
site_name: 'User Documentation'
site_description: 'InvenioRDM user documentation web site'
site_url: 'https://inveniordm.docs.cern.ch'

# Repository
repo_name: 'docs-invenio-rdm'
repo_url: 'https://github.com/inveniosoftware/docs-invenio-rdm'

# Copyright
copyright: 'Copyright &copy; 2019-2020 CERN and Northwestern University.'

# Configuration
theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'white'
  font:
    text: 'Open Sans'
    code: 'Roboto Mono'
  logo: 'images/logo-rdm.png'
  favicon: 'images/favicon.ico'
  feature:
    tabs: true

nav:
  - Home: 'index.md'
  - Install: 'install/index.md'
  - Preview: 'preview/index.md'
  - Develop:
    - Getting Started: 'develop/index.md'
    - Install Locally: 'develop/install_locally.md'
    - Run: 'develop/run.md'
    - Configuration: 'develop/config.md'
    - Customization: 'develop/customize.md'
    - Troubleshooting: 'develop/troubleshoot.md'
    - Cleanup: 'develop/cleanup.md'
  - Extensions:
    - Add your extensions: 'extensions/custom.md'
  - Deploy:
    - Kubernetes: 'deployment/kubernetes.md'
    - OpenShift: 'deployment/openshift.md'


# Customization
extra:
  social:
  - type: 'github'
    link: 'https://github.com/inveniosoftware'
  - type: 'twitter'
    link: 'https://twitter.com/inveniosoftware'
  - type: 'comments'
    link: 'https://invenio-talk.web.cern.ch/c/projects/invenio-rdm'
  - type: 'globe'
    link: 'https://inveniosoftware.org/products/rdm/'
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
